// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/lyric.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lyric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SongTitle string `protobuf:"bytes,2,opt,name=song_title,json=songTitle,proto3" json:"song_title,omitempty"`
	Duration  int32  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Order     int32  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	Content   string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Lyric) Reset() {
	*x = Lyric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lyric_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lyric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lyric) ProtoMessage() {}

func (x *Lyric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lyric_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lyric.ProtoReflect.Descriptor instead.
func (*Lyric) Descriptor() ([]byte, []int) {
	return file_proto_lyric_proto_rawDescGZIP(), []int{0}
}

func (x *Lyric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lyric) GetSongTitle() string {
	if x != nil {
		return x.SongTitle
	}
	return ""
}

func (x *Lyric) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Lyric) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Lyric) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetSongLyricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SongTitle string `protobuf:"bytes,1,opt,name=song_title,json=songTitle,proto3" json:"song_title,omitempty"`
}

func (x *GetSongLyricsRequest) Reset() {
	*x = GetSongLyricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lyric_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSongLyricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongLyricsRequest) ProtoMessage() {}

func (x *GetSongLyricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lyric_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongLyricsRequest.ProtoReflect.Descriptor instead.
func (*GetSongLyricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lyric_proto_rawDescGZIP(), []int{1}
}

func (x *GetSongLyricsRequest) GetSongTitle() string {
	if x != nil {
		return x.SongTitle
	}
	return ""
}

type SongLyrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lyrics []*Lyric `protobuf:"bytes,1,rep,name=lyrics,proto3" json:"lyrics,omitempty"`
}

func (x *SongLyrics) Reset() {
	*x = SongLyrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lyric_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SongLyrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongLyrics) ProtoMessage() {}

func (x *SongLyrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lyric_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongLyrics.ProtoReflect.Descriptor instead.
func (*SongLyrics) Descriptor() ([]byte, []int) {
	return file_proto_lyric_proto_rawDescGZIP(), []int{2}
}

func (x *SongLyrics) GetLyrics() []*Lyric {
	if x != nil {
		return x.Lyrics
	}
	return nil
}

type UpdateLyricRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SongTitle string `protobuf:"bytes,2,opt,name=song_title,json=songTitle,proto3" json:"song_title,omitempty"`
	Duration  int32  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Order     int32  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	Content   string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *UpdateLyricRequest) Reset() {
	*x = UpdateLyricRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lyric_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLyricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLyricRequest) ProtoMessage() {}

func (x *UpdateLyricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lyric_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLyricRequest.ProtoReflect.Descriptor instead.
func (*UpdateLyricRequest) Descriptor() ([]byte, []int) {
	return file_proto_lyric_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLyricRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLyricRequest) GetSongTitle() string {
	if x != nil {
		return x.SongTitle
	}
	return ""
}

func (x *UpdateLyricRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UpdateLyricRequest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *UpdateLyricRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_lyric_proto protoreflect.FileDescriptor

var file_proto_lyric_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x79, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x79, 0x72, 0x69, 0x63, 0x22, 0x82, 0x01, 0x0a, 0x05, 0x4c,
	0x79, 0x72, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x6e, 0x67, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x35, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6e, 0x67, 0x4c, 0x79, 0x72, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6e, 0x67, 0x5f,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x6e,
	0x67, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x32, 0x0a, 0x0a, 0x53, 0x6f, 0x6e, 0x67, 0x4c, 0x79,
	0x72, 0x69, 0x63, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x6c, 0x79, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x79, 0x72, 0x69, 0x63, 0x2e, 0x4c, 0x79, 0x72,
	0x69, 0x63, 0x52, 0x06, 0x6c, 0x79, 0x72, 0x69, 0x63, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x79, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x6e, 0x67, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0xb2, 0x01, 0x0a,
	0x0c, 0x4c, 0x79, 0x72, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a,
	0x08, 0x41, 0x64, 0x64, 0x4c, 0x79, 0x72, 0x69, 0x63, 0x12, 0x0c, 0x2e, 0x6c, 0x79, 0x72, 0x69,
	0x63, 0x2e, 0x4c, 0x79, 0x72, 0x69, 0x63, 0x1a, 0x0c, 0x2e, 0x6c, 0x79, 0x72, 0x69, 0x63, 0x2e,
	0x4c, 0x79, 0x72, 0x69, 0x63, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x6f,
	0x6e, 0x67, 0x4c, 0x79, 0x72, 0x69, 0x63, 0x73, 0x12, 0x1b, 0x2e, 0x6c, 0x79, 0x72, 0x69, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6e, 0x67, 0x4c, 0x79, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x6c, 0x79, 0x72, 0x69, 0x63, 0x2e, 0x4c, 0x79,
	0x72, 0x69, 0x63, 0x22, 0x00, 0x30, 0x01, 0x12, 0x38, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4c, 0x79, 0x72, 0x69, 0x63, 0x12, 0x19, 0x2e, 0x6c, 0x79, 0x72, 0x69, 0x63, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x79, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x6c, 0x79, 0x72, 0x69, 0x63, 0x2e, 0x4c, 0x79, 0x72, 0x69, 0x63, 0x22,
	0x00, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x68, 0x61, 0x72, 0x69, 0x74, 0x73, 0x72, 0x69, 0x7a, 0x6b, 0x61, 0x6c, 0x6c, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lyric_proto_rawDescOnce sync.Once
	file_proto_lyric_proto_rawDescData = file_proto_lyric_proto_rawDesc
)

func file_proto_lyric_proto_rawDescGZIP() []byte {
	file_proto_lyric_proto_rawDescOnce.Do(func() {
		file_proto_lyric_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lyric_proto_rawDescData)
	})
	return file_proto_lyric_proto_rawDescData
}

var file_proto_lyric_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_lyric_proto_goTypes = []interface{}{
	(*Lyric)(nil),                // 0: lyric.Lyric
	(*GetSongLyricsRequest)(nil), // 1: lyric.GetSongLyricsRequest
	(*SongLyrics)(nil),           // 2: lyric.SongLyrics
	(*UpdateLyricRequest)(nil),   // 3: lyric.UpdateLyricRequest
}
var file_proto_lyric_proto_depIdxs = []int32{
	0, // 0: lyric.SongLyrics.lyrics:type_name -> lyric.Lyric
	0, // 1: lyric.LyricService.AddLyric:input_type -> lyric.Lyric
	1, // 2: lyric.LyricService.GetSongLyrics:input_type -> lyric.GetSongLyricsRequest
	3, // 3: lyric.LyricService.UpdateLyric:input_type -> lyric.UpdateLyricRequest
	0, // 4: lyric.LyricService.AddLyric:output_type -> lyric.Lyric
	0, // 5: lyric.LyricService.GetSongLyrics:output_type -> lyric.Lyric
	0, // 6: lyric.LyricService.UpdateLyric:output_type -> lyric.Lyric
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_lyric_proto_init() }
func file_proto_lyric_proto_init() {
	if File_proto_lyric_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lyric_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lyric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lyric_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSongLyricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lyric_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SongLyrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lyric_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLyricRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lyric_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lyric_proto_goTypes,
		DependencyIndexes: file_proto_lyric_proto_depIdxs,
		MessageInfos:      file_proto_lyric_proto_msgTypes,
	}.Build()
	File_proto_lyric_proto = out.File
	file_proto_lyric_proto_rawDesc = nil
	file_proto_lyric_proto_goTypes = nil
	file_proto_lyric_proto_depIdxs = nil
}
